/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Saúl
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jpResult = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        btnViewMode = new javax.swing.JButton();
        btnClose = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        jpDesk = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnPorc = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPount = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(337, 518));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpResult.setBackground(new java.awt.Color(255, 255, 255));

        lblResult.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        lblResult.setForeground(new java.awt.Color(83, 98, 107));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnViewMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnDarkMode.png"))); // NOI18N
        btnViewMode.setActionCommand("mode");
        btnViewMode.setBorderPainted(false);
        btnViewMode.setFocusPainted(false);
        btnViewMode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewMode.setPreferredSize(new java.awt.Dimension(30, 15));
        btnViewMode.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnDarkMode.png"))); // NOI18N

        btnClose.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 0, 0));
        btnClose.setText("●");
        btnClose.setMaximumSize(new java.awt.Dimension(15, 15));
        btnClose.setMinimumSize(new java.awt.Dimension(15, 15));
        btnClose.setPreferredSize(new java.awt.Dimension(15, 15));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMin.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnMin.setForeground(new java.awt.Color(255, 204, 0));
        btnMin.setText("●");
        btnMin.setMaximumSize(new java.awt.Dimension(15, 15));
        btnMin.setMinimumSize(new java.awt.Dimension(15, 15));
        btnMin.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jpResultLayout = new javax.swing.GroupLayout(jpResult);
        jpResult.setLayout(jpResultLayout);
        jpResultLayout.setHorizontalGroup(
            jpResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpResultLayout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(btnViewMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jpResultLayout.createSequentialGroup()
                        .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jpResultLayout.setVerticalGroup(
            jpResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpResultLayout.createSequentialGroup()
                .addGroup(jpResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpResultLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(btnViewMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jpResultLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jpResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 120));

        jpDesk.setBackground(new java.awt.Color(255, 255, 255));

        btnDelete.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1.png"))); // NOI18N
        btnDelete.setText("C");
        btnDelete.setBorder(null);
        btnDelete.setFocusPainted(false);
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1.png"))); // NOI18N
        btnDelete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExp.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnExp.setForeground(new java.awt.Color(100, 54, 156));
        btnExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnExp.setText("^");
        btnExp.setBorder(null);
        btnExp.setFocusPainted(false);
        btnExp.setFocusable(false);
        btnExp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnExp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnPorc.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnPorc.setForeground(new java.awt.Color(100, 54, 156));
        btnPorc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnPorc.setText("%");
        btnPorc.setBorder(null);
        btnPorc.setFocusPainted(false);
        btnPorc.setFocusable(false);
        btnPorc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPorc.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnPorc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnDiv.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnDiv.setForeground(new java.awt.Color(100, 54, 156));
        btnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnDiv.setText("/");
        btnDiv.setBorder(null);
        btnDiv.setFocusPainted(false);
        btnDiv.setFocusable(false);
        btnDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiv.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnDiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnMulti.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnMulti.setForeground(new java.awt.Color(100, 54, 156));
        btnMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnMulti.setText("X");
        btnMulti.setBorder(null);
        btnMulti.setFocusPainted(false);
        btnMulti.setFocusable(false);
        btnMulti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMulti.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnMulti.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnMinus.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(100, 54, 156));
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnMinus.setText("-");
        btnMinus.setBorder(null);
        btnMinus.setFocusPainted(false);
        btnMinus.setFocusable(false);
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnMinus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnPlus.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(100, 54, 156));
        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnPlus.setText("+");
        btnPlus.setBorder(null);
        btnPlus.setFocusPainted(false);
        btnPlus.setFocusable(false);
        btnPlus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2.png"))); // NOI18N
        btnPlus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn2_pressed.png"))); // NOI18N

        btnResult.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnResult.setForeground(new java.awt.Color(255, 255, 255));
        btnResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3.png"))); // NOI18N
        btnResult.setText("=");
        btnResult.setBorder(null);
        btnResult.setFocusPainted(false);
        btnResult.setFocusable(false);
        btnResult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResult.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3.png"))); // NOI18N
        btnResult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn3_pressed.png"))); // NOI18N

        btn9.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(83, 98, 107));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.setFocusPainted(false);
        btn9.setFocusable(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn6.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn6.setForeground(new java.awt.Color(83, 98, 107));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.setFocusPainted(false);
        btn6.setFocusable(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn3.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(83, 98, 107));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.setFocusPainted(false);
        btn3.setFocusable(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn8.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(83, 98, 107));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.setFocusPainted(false);
        btn8.setFocusable(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(83, 98, 107));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.setFocusPainted(false);
        btn5.setFocusable(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn2.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(83, 98, 107));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.setFocusPainted(false);
        btn2.setFocusable(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn7.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(83, 98, 107));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.setFocusPainted(false);
        btn7.setFocusable(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn4.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(83, 98, 107));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.setFocusPainted(false);
        btn4.setFocusable(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn1.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(83, 98, 107));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.setFocusPainted(false);
        btn1.setFocusable(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btnPount.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btnPount.setForeground(new java.awt.Color(83, 98, 107));
        btnPount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btnPount.setText(".");
        btnPount.setBorder(null);
        btnPount.setFocusPainted(false);
        btnPount.setFocusable(false);
        btnPount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPount.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btnPount.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N

        btn0.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(83, 98, 107));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.setFocusPainted(false);
        btn0.setFocusable(false);
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn4.png"))); // NOI18N
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn1_pressed.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpDeskLayout = new javax.swing.GroupLayout(jpDesk);
        jpDesk.setLayout(jpDeskLayout);
        jpDeskLayout.setHorizontalGroup(
            jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDeskLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDeskLayout.createSequentialGroup()
                        .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpDeskLayout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(30, 30, 30)
                                .addComponent(btnExp))
                            .addGroup(jpDeskLayout.createSequentialGroup()
                                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1)
                                    .addComponent(btn7)
                                    .addComponent(btn4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2)
                                    .addComponent(btn8)
                                    .addComponent(btn5)
                                    .addComponent(btn0))))
                        .addGap(31, 31, 31)
                        .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPorc)
                            .addComponent(btn3)
                            .addComponent(btn9)
                            .addComponent(btn6)))
                    .addComponent(btnPount))
                .addGap(28, 28, 28)
                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlus)
                    .addComponent(btnMulti)
                    .addComponent(btnDiv)
                    .addComponent(btnMinus)
                    .addComponent(btnResult))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jpDeskLayout.setVerticalGroup(
            jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDeskLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnExp)
                    .addComponent(btnPorc)
                    .addComponent(btnDiv))
                .addGap(28, 28, 28)
                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDeskLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btn6)
                        .addGap(28, 28, 28)
                        .addComponent(btn3))
                    .addGroup(jpDeskLayout.createSequentialGroup()
                        .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDeskLayout.createSequentialGroup()
                                .addComponent(btnMulti)
                                .addGap(28, 28, 28)
                                .addComponent(btnMinus)
                                .addGap(28, 28, 28)
                                .addComponent(btnPlus))
                            .addGroup(jpDeskLayout.createSequentialGroup()
                                .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn8)
                                    .addComponent(btn9))
                                .addGap(28, 28, 28)
                                .addComponent(btn5)
                                .addGap(28, 28, 28)
                                .addComponent(btn2))
                            .addGroup(jpDeskLayout.createSequentialGroup()
                                .addComponent(btn7)
                                .addGap(28, 28, 28)
                                .addComponent(btn4)
                                .addGap(28, 28, 28)
                                .addComponent(btn1)))
                        .addGap(28, 28, 28)
                        .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPount)
                                .addComponent(btn0))
                            .addComponent(btnResult))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jpDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
            }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JLabel btnClose;
    public javax.swing.JButton btnDelete;
    public javax.swing.JButton btnDiv;
    public javax.swing.JButton btnExp;
    public javax.swing.JLabel btnMin;
    public javax.swing.JButton btnMinus;
    public javax.swing.JButton btnMulti;
    public javax.swing.JButton btnPlus;
    public javax.swing.JButton btnPorc;
    public javax.swing.JButton btnPount;
    public javax.swing.JButton btnResult;
    public javax.swing.JButton btnViewMode;
    private javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JPanel jpDesk;
    public javax.swing.JPanel jpResult;
    public javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables
}
